### ISSUE TITLE
Non-owned events are not showing in tournament summary 

### ISSUE THREAD

**Issue by sprintska** [Valadian/T4#28] opened 2022-10-31 19:49 UTC
I can't see any events which aren't either 1) owned by me or 2) manually created in Hasura in the Event List page.

**Comment by Valadian** [comment] 2022-10-31 19:51
this is a duplicate of #23 

by design, tournaments are not visible until made public. UI doesn't have a toggle to make public

**Comment by sprintska** [comment] 2022-10-31 19:55
Ack

**Closed** 2022-10-31 19:54 UTC
